### ISSUE TITLE
Two login forms sometimes appearing

### ISSUE THREAD

**Issue by mkrakiewicz** [piwik/plugin-LoginLdap#136] opened 2016-05-31 10:02 UTC
In some cases the plugin causes two login forms to appear.
Steps to reproduce:
1. Set correct REMOTE_USER variable in .htaccess file (for existing LDAP user)
2. Set incorrect REMOTE_USER
3. Refresh
![image](https://cloud.githubusercontent.com/assets/17594718/15670727/3866a148-2727-11e6-90b5-59232502d260.png)

**Comment by mattab** [comment] 2017-01-04 09:53
Please submit pull request if possible :+1: as we could not reproduce in standard use case, closing

**Closed by mattab** 2017-01-04 09:53 UTC
