### ISSUE TITLE
Enabling 2fa we get "The plugin Login is not enabled. You can activate the plugin on Settings > Plugins page in Matomo."

### ISSUE THREAD

**Issue by paladox** [piwik/plugin-LoginLdap#220] opened 2020-11-16 19:49 UTC
Hi, when one of our users tries to enable 2fa they are getting "The plugin Login is not enabled. You can activate the plugin on Settings > Plugins page in Matomo."

Could this be fixed please?

**Comment by tsteur** [comment] 2020-11-16 19:59
Hi @paladox thanks for creating this issue. I'm closing this as a duplicate of https://github.com/matomo-org/plugin-LoginLdap/issues/181 We have fixed this already in Matomo 4 (which should be released in about one week) and we also backported the fixes to 3.X but we haven't released a new version of Matomo yet (might take a while until there's a new release)

**Closed as completed by tsteur** 2020-11-16 19:59 UTC
Labels: duplicate
